name: example
description: A flutter example of dynamic forms project with default components.
version: 0.2.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dynamic_forms_components:
    path: ../
  flutter_bloc: ^7.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/test_form1.xml
    - assets/test_form1.json
    - assets/transition_form1.xml
    - assets/transition_form2.xml
    - assets/transition_form3.xml
