name: dynamic_forms
description: Dart library providing infrastructure to parse complex external form with expressions into a custom model.
version: 0.11.0
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  xml: ^3.5.0
  uuid: ^2.0.4
  quiver: ^2.0.5
  rxdart: ^0.23.1
  meta: ^1.1.8

  expression_language:
    git:
      url: https://github.com/OndrejKunc/flutter_dynamic_forms.git
      path: packages/expression_language

dev_dependencies:
  test: ^1.9.4
  test_coverage: ^0.4.0
  pedantic: ^1.9.0
