name: flutter_dynamic_forms_components
description: Flutter package containing default set of dynamic form components.
version: 0.7.3
author: Ond≈ôej Kunc <kunc.ondrej1@gmail.com>
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dynamic_forms:
    git:
      url: https://github.com/OndrejKunc/flutter_dynamic_forms.git
      path: packages/flutter_dynamic_forms

  intl: ^0.16.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  dynamic_forms_generator:
    git:
      url: https://github.com/OndrejKunc/flutter_dynamic_forms.git
      path: packages/dynamic_forms_generator

flutter: