name: dynamic_forms_generator
description: Library for generating model and parser part of the dynamic forms.
version: 0.5.1
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build: ^1.0.0
  build_config: '>=0.2.6 <0.5.0'
  yaml: ^2.2.0
  petitparser: ^2.4.0
  meta: ^1.1.8

dev_dependencies:
  test: ^1.6.3
  pedantic: ^1.9.0