name: flutter_dynamic_forms
description: A flutter project providing infrastructure to render dynamic forms.
version: 0.8.0
author: Ond≈ôej Kunc <kunc.ondrej1@gmail.com>
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_forms:
    git:
        url: https://github.com/OndrejKunc/flutter_dynamic_forms.git
        path: packages/dynamic_forms

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: