name: flutter_dynamic_forms
description: A flutter project providing infrastructure to render dynamic forms.
version: 1.0.0
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  provider: ^5.0.0

  expression_language:
    path: ../expression_language
  dynamic_forms:
    path: ../dynamic_forms

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
