name: flutter_dynamic_forms
description: A flutter project providing infrastructure to render dynamic forms.
version: 0.13.0
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  provider: ^4.1.3

  dynamic_forms:
    git:
      url: https://github.com/OndrejKunc/flutter_dynamic_forms.git
      path: packages/dynamic_forms

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
