name: expression_language
description: Library for parsing and evaluating simple expression language with additional references
version: 1.0.1
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  petitparser: ^4.0.0
  rational: ^1.0.0

dev_dependencies:
  test: ^1.16.0
  gherkin: ^1.1.5+1
  glob: ^1.2.0
  pedantic: ^1.11.0
