name: expression_language
description: Library for parsing and evaluating simple expression language with additional references
version: 0.0.1
author: Ond≈ôej Kunc <kunc.ondrej1@gmail.com>
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  petitparser: ^2.1.1
  rational: ^0.3.0

dev_dependencies:
  test: ^1.6.3
  test_coverage: ^0.2.3 #Bump to higher version when dart sdk 2.3.0 is available with flutter stable
  gherkin: ^1.0.4